# Generated by Django 5.0.6 on 2024-06-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('Marca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('cantidad_pasajeros', models.CharField(max_length=20)),
                ('annio', models.DateField()),
                ('tipo_vehiculo', models.CharField(max_length=45)),
                ('combustible', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('valor', models.IntegerField(blank=True, max_length=50, null=True)),
                ('id_auto', models.ForeignKey(db_column='idauto', on_delete=django.db.models.deletion.CASCADE, to='rent.auto')),
            ],
        ),
    ]
