# Generated by Django 5.0.6 on 2024-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
